/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - email
 *         - password
 *
 *       properties:
 *         id:
 *            type: number
 *            description: The auto-generated id
 *         email:
 *            type: string
 *            description: User email
 *         password:
 *            type: string
 *            description: User password
 *         isActivate:
 *            type: boolean
 *            description: Autogenerated status of email activated
 *         activationLink:
 *            type: string
 *            description: Autogenerated link and send to user email
 *         role:
 *            type: string
 *            description: User roles
 *
 *       example:
 *        id: 3
 *        email: testmail@gmail.com
 *        password: qwerty12345
 *        isActivate: true
 *        activationLink: http://boncho.com/fsdgreg34r543tgs5tgfgfds
 *        role: user
 */

/**
 * @swagger
 * tags:
 *   name: Registration/Authorization
 *   description: The Reg/Auth in API
 */

/**
 * @swagger
 * /api/user/registration:
 *   post:
 *     summary: Registration a new user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *              schema:
 *              type: object
 *              properties:
 *                  email:
 *                      type: string
 *                      description: User email
 *                  password:
 *                      type: string
 *                      description: User password *
 *              example:
 *                  email: testemail@gmail.com
 *                  password: qwerty1355
 *     responses:
 *       200:
 *         description: New user was successfully created
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       500:
 *         description: Some server error
 */

